"""empty message

Revision ID: ab530bfdf2b2
Revises: e6bdbf9b0620
Create Date: 2024-02-21 15:53:24.295257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab530bfdf2b2'
down_revision = 'e6bdbf9b0620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('g_auth_verify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g_auth_verify', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
