"""empty message

Revision ID: ccaaf00b1410
Revises: ab530bfdf2b2
Create Date: 2024-02-22 14:52:43.336025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaaf00b1410'
down_revision = 'ab530bfdf2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g_auth_verify', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('g_auth_verify')

    # ### end Alembic commands ###
