"""empty message

Revision ID: e6bdbf9b0620
Revises: 91b0f7f022ab
Create Date: 2024-02-21 14:11:53.590102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bdbf9b0620'
down_revision = '91b0f7f022ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g_auth_verify', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('g_auth_verify')

    # ### end Alembic commands ###
